GnuPG failure status parsing
...for decryption. Encryption to follow :P

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -331,6 +331,53 @@ get_key() {
   echo "${valid_keys[$(( choice - 1 ))]}"
 }
 
+parse_gpg_failures() {
+  # Return a human readable list GnuPG's status failures (modulo their
+  # relevance to secrets); or return nothing, if everything's OK
+  local status="$1"
+
+  "${AWK}" -F" " '
+    $2 == "BADSIG" || $2 == "ERRSIG"        { print "* Cannot verify signature" }
+    $2 == "KEYREVOKED" || $2 == "REVKEYSIG" { print "* The key " $3 " has been revoked" }
+    $2 == "BAD_PASSPHRASE"                  { print "* The passphrase was wrong or missing" }
+    $2 == "NO_PUBKEY"                       { print "* The public key " $3 " is not available" }
+    $2 == "NO_SECKEY"                       { print "* The secret key " $3 " is not available" }
+    $2 == "NODATA" && $3 == "1"             { print "* No armoured data found" }
+    $2 == "NODATA" && $3 == "2"             { print "* No OpenPGP packets found" }
+    $2 == "NODATA" && $3 == "3"             { print "* Invalid OpenPGP packets found" }
+    $2 == "NODATA" && $3 == "4"             { print "* No signature found" }
+    $2 == "UNEXPECTED"                      { print "* Unexpected data found" }
+    $2 == "FAILURE"                         { print "* General GnuPG failure" }
+  ' <<< "${status}"
+}
+
+decrypt() {
+  # Decrypt the given file to stdout
+  local filename="$1"
+
+  # Setup a temporary file and file descriptor for the GnuPG status
+  local status_file="$(mktemp)"
+  exec 3>"${status_file}"
+
+  # Attempt to decrypt
+  local secrets="$("${GPG}" --status-fd 3 --decrypt "${filename}" 2>/dev/null)"
+
+  # Read in status and clean up
+  local status="$(<"${status_file}")"
+  exec 3>&-
+  rm -f "${status_file}"
+
+  # Parse the GnuPG status to determine if anything went wrong
+  local failure="$(parse_gpg_failures "${status}")"
+  if [[ "${failure}" ]]; then
+    stderr "Your secrets have been compromised! Flee immediately!"
+    >&2 echo "${failure}"
+    return 1
+  fi
+
+  echo "${secrets}"
+}
+
 ## Blockchain Functions ################################################
 
 # We have a global blockchain... Gross, but bash isn't great at passing
@@ -348,11 +395,7 @@ read_blockchain() {
   if [[ -e "${filename}" ]]; then
     # Attempt to load blockchain from file
     local secrets
-    if ! secrets="$("${GPG}" --decrypt "${filename}" 2>/dev/null)"; then
-      stderr "Couldn't decrypt or validate ${filename}!"
-      exit 1
-    fi
-
+    if ! secrets="$(decrypt "${filename}")"; then exit 1; fi
     readarray -t BLOCKCHAIN <<< "${secrets}"
 
     # Validate the last block on every block
