Blockchain validation functions

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -21,6 +21,8 @@ GPG="gpg"
 AWK="awk"
 SHA256="sha256sum"
 
+NULL_DIGEST="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
+
 ## Utility Functions ###################################################
 
 stderr() {
@@ -364,7 +366,7 @@ add_block() {
       stderr "Invalid type for genesis block!"
       exit 1
     fi
-    prev_digest="$(sha256 "")"
+    prev_digest="${NULL_DIGEST}"
 
   else
     if [[ "${block_type}" == "create" ]]; then
@@ -372,8 +374,11 @@ add_block() {
       exit 1
     fi
     local prev_block="${BLOCKCHAIN[-1]}"
-    prev_digest="$(${AWK} -F'\t' '{ print $NF }' <<< "$prev_block")"
+    prev_digest="$(rev <<< "${prev_block}" | cut -f1 | rev)"
   fi
+
+  # This can take a while, so let the user know what's going on
+  >&2 echo -n "Calculating block... "
 
   local base_block="${block_type}	$(whoami)	$(date +%s)"
   local nonce_block
@@ -393,19 +398,79 @@ add_block() {
   # Add block to the chain
   block="${nonce_block}	${block_digest}"
   BLOCKCHAIN+=("${block}")
+  >&2 echo "Done!"
 }
 
-## Common ##############################################################
-
-create_new_secrets_file() {
-  local filename="$(echo "$1")"
-
+add_genesis_block() {
+  # NOTE his will fail downstream if the blockchain is already initialised
   local sign_key="$(get_key sign)"
   local encrypt_key="$(get_key encrypt)"
 
   add_block "create" "${sign_key}" "${encrypt_key}"
-  write_blockchain "${filename}"
 }
+
+validate_block() {
+  # Validate the hash of a specific block
+  local index="$1"
+  local chain_length="${#BLOCKCHAIN[@]}"
+
+  # Can't validate empty chain
+  if (( chain_length == 0 )); then
+    return 1
+  fi
+
+  # Normalise index
+  if (( index < 0 )); then
+    index="$(( chain_length + index ))"
+  fi
+
+  # Check index bounds
+  if (( index < 0 )) || (( index >= chain_length )); then
+    return 1
+  fi
+
+  local block="${BLOCKCHAIN[${index}]}"
+  local block_digest="$(rev <<< "${block}" | cut -f1 | rev)"
+  local digestless_block="$(rev <<< "${block}" | cut -f2- | rev )"
+
+  local prev_digest
+  if (( index == 0 )); then
+    prev_digest="${NULL_DIGEST}"
+  else
+    local prev_block="${BLOCKCHAIN[$(( index - 1 ))]}"
+    prev_digest="$(rev <<< "${prev_block}" | cut -f1 | rev)"
+  fi
+
+  local calc_digest="$(sha256 "${prev_digest}:$(sha256 "${digestless_block}")")"
+  if [[ "${block_digest}" != "${calc_digest}" ]]; then
+    return 1
+  fi
+}
+
+validate_chain() {
+  # Validate the tail (and potentially all) of the chain
+  local blocks="${1:-0}"
+  local chain_length="${#BLOCKCHAIN[@]}"
+
+  # Can't validate empty chain
+  if (( chain_length == 0 )); then
+    return 1
+  fi
+
+  # Validate everything
+  if (( blocks == 0 )) || (( blocks > chain_length )); then
+    blocks="${chain_length}"
+  fi
+
+  for index in $(seq -1 -${blocks}); do
+    if ! validate_block "${index}"; then
+      return 1
+    fi
+  done
+}
+
+## Common ##############################################################
+
 
 ## Keep a Secret #######################################################
 
