Analyse GnuPG status messages for sign/encrypt failures

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -9,7 +9,7 @@
 
 BINARY="$0"
 PROGNAME="$(basename "${BINARY}")"
-VERSION="0.1.1"
+VERSION="0.2.0"
 
 OS="$(uname -s)"
 COPY=""
@@ -332,12 +332,14 @@ get_key() {
   echo "${valid_keys[$(( choice - 1 ))]}"
 }
 
-parse_gpg_failures() {
+human_readable_gpg_status() {
   # Return a human readable list GnuPG's status failures (modulo their
   # relevance to secrets); or return nothing, if everything's OK
   local status="$1"
 
   "${AWK}" -F" " '
+    $2 == "INV_RECP" || $2 == "NO_RECP"     { print "* Invalid encryption key" }
+    $2 == "INV_SGNR" || $2 == "NO_SGNR"     { print "* Invalid signing key" }
     $2 == "BADSIG" || $2 == "ERRSIG"        { print "* Cannot verify signature" }
     $2 == "KEYREVOKED" || $2 == "REVKEYSIG" { print "* The key " $3 " has been revoked" }
     $2 == "BAD_PASSPHRASE"                  { print "* The passphrase was wrong or missing" }
@@ -350,6 +352,35 @@ parse_gpg_failures() {
     $2 == "UNEXPECTED"                      { print "* Unexpected data found" }
     $2 == "FAILURE"                         { print "* General GnuPG failure" }
   ' <<< "${status}"
+}
+
+sign_and_encrypt() {
+  # Sign and encrypt stdin and write to file
+  local sign_key="$1"
+  local encrypt_key="$2"
+  local filename="$3"
+
+  # Setup a temporary file and file descriptor for the GnuPG status
+  local status_file="$(mktemp)"
+  exec 3>"${status_file}"
+
+  # Attempt to sign and encrypt
+  "${GPG}" --sign --local-user "${sign_key}" \
+           --encrypt --recipient "${encrypt_key}" \
+           --yes --status-fd 3 --output "${filename}" 2>/dev/null
+
+  # Read in status and clean up
+  local status="$(<"${status_file}")"
+  exec 3>&-
+  rm -f "${status_file}"
+
+  # Parse the GnuPG status to determine if anything went wrong
+  local failure="$(human_readable_gpg_status "${status}")"
+  if [[ "${failure}" ]]; then
+    stderr "Your secrets could not be securely contained!"
+    >&2 echo "${failure}"
+    return 1
+  fi
 }
 
 decrypt() {
@@ -369,7 +400,7 @@ decrypt() {
   rm -f "${status_file}"
 
   # Parse the GnuPG status to determine if anything went wrong
-  local failure="$(parse_gpg_failures "${status}")"
+  local failure="$(human_readable_gpg_status "${status}")"
   if [[ "${failure}" ]]; then
     stderr "Your secrets have been compromised! Flee immediately!"
     >&2 echo "${failure}"
@@ -437,11 +468,11 @@ write_blockchain() {
   local sign_key="$(cut -f4 <<< "${genesis_block}")"
   local encrypt_key="$(cut -f5 <<< "${genesis_block}")"
 
-  # Encrypt and sign blockchain to disk
-  for block in "${BLOCKCHAIN[@]}"; do echo "${block}"; done \
-  | "${GPG}" --sign --local-user "${sign_key}" \
-             --encrypt --recipient "${encrypt_key}" \
-             --yes --output "${filename}" 2>/dev/null
+  # Sign and encrypt the blockchain to disk
+  if ! for block in "${BLOCKCHAIN[@]}"; do echo "${block}"; done \
+       | sign_and_encrypt "${sign_key}" "${encrypt_key}" "${filename}"; then
+    exit 1
+  fi
 }
 
 add_block() {
