Expanded documentation on blockchain maintenance

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -406,6 +406,7 @@ read_blockchain() {
 
     if ! validate_chain "${to_validate}"; then
       stderr "Your secrets have been compromised! Flee immediately!"
+      >&2 echo "* The blockchain could not be validated"
       exit 1
     fi
 
