Better dependency management

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -18,7 +18,7 @@ PASTE=""
 GPG="gpg"
 AWK="awk"
 SHA256="sha256sum"
-SHUF="posix_shuf"
+SHUF="shuf"
 
 NULL_DIGEST="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
 
@@ -34,15 +34,6 @@ stderr() {
   fi
 
   >&2 echo -e "${message}"
-}
-
-has_dependencies() {
-  # Check dependencies exist as commands
-  local -a deps=("$@")
-
-  for cmd in "${deps[@]}"; do
-    command -v -- "${cmd}" &>/dev/null
-  done
 }
 
 escape() {
@@ -96,6 +87,32 @@ god_mode() {
   # Trap and ignore SIGHUP, SIGINT and SIGTERM
   local message="$*"
   trap "stderr \"${message}\"" SIGHUP SIGINT SIGTERM
+}
+
+## Dependency Management Functions #####################################
+
+has_dependencies() {
+  # Check dependencies exist as commands
+  local -a deps=("$@")
+
+  for cmd in "${deps[@]}"; do
+    command -v -- "${cmd}" &>/dev/null
+  done
+}
+
+best_dependency() {
+  # Return the first existing command from a list of dependencies
+  local -a deps=("$@")
+
+  for cmd in "${deps[@]}"; do
+    if has_dependencies "${cmd}"; then
+      echo "${cmd}"
+      return 0
+    fi
+  done
+
+  # None found :(
+  return 1
 }
 
 ## Usage/Help Functions ################################################
@@ -239,6 +256,30 @@ paste() {
 # NOTE The --with-colons output for key listings and --status-fd output
 # for GnuPG run status is described in the GnuPG distribution: doc/DETAILS
 # http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob_plain;f=doc/DETAILS
+
+gpg_version() {
+  # Get the GnuPG version of a particular binary
+  local gpg_bin="$1"
+
+  if has_dependencies "${gpg_bin}"; then
+    "${gpg_bin}" --list-config --with-colons 2>/dev/null \
+    | "${AWK}" -F: -v BIN="${gpg_bin}" '$1 == "cfg" && $2 == "version" { print $3 ":" BIN }'
+  fi
+}
+
+best_gpg() {
+  # Get the latest GnuPG binary in the path
+
+  if ! best_dependency gpg gpg2 >/dev/null; then
+    # Fail if there's no GnuPG in the path
+    return 1
+  fi
+
+  cat <(gpg_version gpg) <(gpg_version gpg2) \
+  | sort -t. -k1,2 -k2,2 -k3,3 -nr \
+  | head -1 \
+  | cut -d: -f2
+}
 
 secret_key_ids() {
   # Output a list of secret key and subkey IDs
@@ -1104,32 +1145,36 @@ main_forget() {
 initialise() {
   # Check dependencies, GnuPG status and initialise the copy and paste
   # functions, if they're available on the host platform
-  if ! has_dependencies "${GPG}"; then
+
+  # We need GNU or vanilla Awk
+  if ! AWK="$(best_dependency gawk awk)"; then
+    stderr "${PROGNAME} requires Awk!"
+    exit 1
+  fi
+
+  # We need GnuPG
+  if ! GPG="$(best_gpg)"; then
     stderr "${PROGNAME} requires GnuPG to be installed!"
     exit 1
   fi
 
   # We need either sha256sum or OpenSSL
-  if ! has_dependencies "${SHA256}"; then
-    if ! has_dependencies openssl; then
-      stderr "${PROGNAME} requires either sha256sum or OpenSSL to calculate SHA256 digests!"
-      exit 1
-    fi
+  if ! SHA256="$(best_dependency sha256sum gsha256sum openssl)"; then
+    stderr "${PROGNAME} requires either sha256sum or OpenSSL to calculate SHA256 digests!"
+    exit 1
+  fi
+
+  if [[ "${SHA256}" = "openssl" ]]; then
+    # OpenSSL takes soem specific arguments to generate the SHA256
     SHA256="openssl dgst -sha256"
   fi
 
-  # shuf > gshuf > posix_shuf
-  has_dependencies gshuf && SHUF="gshuf"
-  has_dependencies shuf  && SHUF="shuf"
+  SHUF="$(best_dependency shuf gshuf posix_shuf)"
 
   if ! has_valid_secret_keys; then
     stderr "No valid encryption or signing keys found!"
     exit 1
   fi
-
-  # Use GnuPG2 and Gnu AWK if they're available
-  has_dependencies gpg2 && GPG="gpg2"
-  has_dependencies gawk && AWK="gawk"
 
   case "${OS}" in
     "Darwin")
