Password generation

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -73,6 +73,17 @@ shuffle() {
   fold -w1 <<< "$*" | ${SHUF} | tr -d "\n"
 }
 
+random_string() {
+  # Create a random string
+  local length="$1"
+  local class="$2"
+
+  LC_CTYPE=C tr -dc "${class}" </dev/urandom \
+  | fold -w "${length}" \
+  | head -1 \
+  || true  # This nullifies the weird non-zero exit code
+}
+
 sha256() {
   # Return the SHA256 digest of the input
   local str="$*"
@@ -504,6 +515,26 @@ validate_chain() {
 
 ## Keep a Secret #######################################################
 
+generate_password() {
+  # Generate password
+  local length="$1"
+  local allowed="$2"
+  local -a must_include=("${@:3}")
+
+  local password=""
+
+  for class in "${must_include[@]}"; do
+    password="${password}$(random_string 1 "${class}")"
+  done
+
+  local remainder="$(( length - "${#must_include[@]}" ))"
+  if (( remainder > 0 )); then
+    password="${password}$(random_string "${remainder}" "${allowed}")"
+  fi
+
+  shuffle "${password}"
+}
+
 main_keep() {
   local arg
   local show_help=""
@@ -515,7 +546,7 @@ main_keep() {
   local secrets_file="~/.secrets"
   local force=""
   local length="16"
-  local allowed="a-zA-Z0-9!?$%&=+_-"
+  local allowed='a-zA-Z0-9!?$%&=+_-'
   local -a must_include=()
   local copy_output=""
   local expire="30"
